<?php
/**
 * Part of the Fuel framework.
 *
 * @package    Fuel
 * @version    1.7
 * @author     Fuel Development Team
 * @license    MIT License
 * @copyright  2010 - 2014 Fuel Development Team
 * @link       http://fuelphp.com
 */
return array(
    /**
     * base_url - The base URL of the application.
     * MUST contain a trailing slash (/)
     *
     * You can set this to a full or relative URL:
     *
     *     'base_url' => '/foo/',
     *     'base_url' => 'http://foo.com/'
     *
     * Set this to null to have it automatically detected.
     */
// 'base_url'  => null,

    /**
     * url_suffix - Any suffix that needs to be added to
     * URL's generated by Fuel. If the suffix is an extension,
     * make sure to include the dot
     *
     *     'url_suffix' => '.html',
     *
     * Set this to an empty string if no suffix is used
     */
// 'url_suffix'  => '',

    /**
     * index_file - The name of the main bootstrap file.
     *
     * Set this to 'index.php if you don't use URL rewriting
     */
// 'index_file' => false,
// 'profiling'  => false,

    /**
     * Default location for the file cache
     */
// 'cache_dir'       => APPPATH.'cache/',

    /**
     * Settings for the file finder cache (the Cache class has it's own config!)
     */
    'caching'         => false,
// 'cache_lifetime'  => 3600, // In Seconds

    /**
     * Callback to use with ob_start(), set this to 'ob_gzhandler' for gzip encoding of output
     */
// 'ob_callback'  => null,
// 'errors'  => array(
// Which errors should we show, but continue execution? You can add the following:
// E_NOTICE, E_WARNING, E_DEPRECATED, E_STRICT to mimic PHP's default behaviour
// (which is to continue on non-fatal errors). We consider this bad practice.
// 'continue_on'  => array(),
// How many errors should we show before we stop showing them? (prevents out-of-memory errors)
// 'throttle'     => 10,
// Should notices from Error::notice() be shown?
// 'notices'      => true,
// Render previous contents or show it as HTML?
// 'render_prior' => false,
// ),

    /**
     * Localization & internationalization settings
     */
// 'language'           => 'en', // Default language
// 'language_fallback'  => 'en', // Fallback language when file isn't available for default language
// 'locale'             => 'en_US', // PHP set_locale() setting, null to not set

    /**
     * Internal string encoding charset
     */
// 'encoding'  => 'UTF-8',

    /**
     * DateTime settings
     *
     * server_gmt_offset	in seconds the server offset from gmt timestamp when time() is used
     * default_timezone		optional, if you want to change the server's default timezone
     */
// 'server_gmt_offset'  => 0,
'default_timezone'   => 'Asia/Tokyo',

    /**
     * Logging Threshold.  Can be set to any of the following:
     *
     * Fuel::L_NONE
     * Fuel::L_ERROR
     * Fuel::L_WARNING
     * Fuel::L_DEBUG
     * Fuel::L_INFO
     * Fuel::L_ALL
     */
// 'log_threshold'    => Fuel::L_WARNING,
// 'log_path'         => APPPATH.'logs/',
// 'log_date_format'  => 'Y-m-d H:i:s',

    /**
     * Security settings
     */
    'security' => array(
//        'csrf_autoload'    => false,
//        'csrf_token_key'   => 'fuel_csrf_token',
//        'csrf_expiration'  => 0,

        /**
         * A salt to make sure the generated security tokens are not predictable
         */
// 'token_salt'            => 'put your salt value here to make the token more secure',

        /**
         * Allow the Input class to use X headers when present
         *
         * Examples of these are HTTP_X_FORWARDED_FOR and HTTP_X_FORWARDED_PROTO, which
         * can be faked which could have security implications
         */
// 'allow_x_headers'       => false,

        /**
         * This input filter can be any normal PHP function as well as 'xss_clean'
         *
         * WARNING: Using xss_clean will cause a performance hit.
         * How much is dependant on how much input data there is.
         */
        'uri_filter' => array('htmlentities'),
        /**
         * This input filter can be any normal PHP function as well as 'xss_clean'
         *
         * WARNING: Using xss_clean will cause a performance hit.
         * How much is dependant on how much input data there is.
         */
// 'input_filter'  => array(),

        /**
         * This output filter can be any normal PHP function as well as 'xss_clean'
         *
         * WARNING: Using xss_clean will cause a performance hit.
         * How much is dependant on how much input data there is.
         */
        'output_filter' => array('Security::htmlentities'),
        /**
         * Encoding mechanism to use on htmlentities()
         */
// 'htmlentities_flags' => ENT_QUOTES,

        /**
         * Wether to encode HTML entities as well
         */
// 'htmlentities_double_encode' => false,

        /**
         * Whether to automatically filter view data
         */
// 'auto_filter_output'  => true,

        /**
         * With output encoding switched on all objects passed will be converted to strings or
         * throw exceptions unless they are instances of the classes in this array.
         */
        'whitelisted_classes' => array(
            'Fuel\\Core\\Presenter',
            'Fuel\\Core\\Response',
            'Fuel\\Core\\View',
            'Fuel\\Core\\ViewModel',
            'Closure',
        ),
    ),
    /**
     * Cookie settings
     */
// 'cookie' => array(
// Number of seconds before the cookie expires
// 'expiration'  => 0,
// Restrict the path that the cookie is available to
// 'path'        => '/',
// Restrict the domain that the cookie is available to
// 'domain'      => null,
// Only transmit cookies over secure connections
// 'secure'      => false,
// Only transmit cookies over HTTP, disabling Javascript access
// 'http_only'   => false,
// ),

    /**
     * Validation settings
     */
// 'validation' => array(
    /**
     * Wether to fallback to global when a value is not found in the input array.
     */
// 'global_input_fallback' => true,
// ),

    /**
     * Controller class prefix
     */
// 'controller_prefix' => 'Controller_',

    /**
     * Routing settings
     */
// 'routing' => array(
    /**
     * Whether URI routing is case sensitive or not
     */
// 'case_sensitive' => true,

    /**
     *  Wether to strip the extension
     */
// 'strip_extension' => true,
// ),

    /**
     * To enable you to split up your application into modules which can be
     * routed by the first uri segment you have to define their basepaths
     * here. By default empty, but to use them you can add something
     * like this:
     *      array(APPPATH.'modules'.DS)
     *
     * Paths MUST end with a directory separator (the DS constant)!
     */
// 'module_paths' => array(
// 	//APPPATH.'modules'.DS
// ),

    /**
     * To enable you to split up your additions to the framework, packages are
     * used. You can define the basepaths for your packages here. By default
     * empty, but to use them you can add something like this:
     *      array(APPPATH.'modules'.DS)
     *
     * Paths MUST end with a directory separator (the DS constant)!
     */
    'package_paths' => array(
        PKGPATH
    ),
    /*     * *********************************************************************** */
    /* Always Load                                                            */
    /*     * *********************************************************************** */
// 'always_load'  => array(

    /**
     * These packages are loaded on Fuel's startup.
     * You can specify them in the following manner:
     *
     * array('auth'); // This will assume the packages are in PKGPATH
     *
     * // Use this format to specify the path to the package explicitly
     * array(
     *     array('auth'	=> PKGPATH.'auth/')
     * );
     */
// 'packages'  => array(
// 	//'orm',
// ),

    /**
     * These modules are always loaded on Fuel's startup. You can specify them
     * in the following manner:
     *
     * array('module_name');
     *
     * A path must be set in module_paths for this to work.
     */
// 'modules'  => array(),

    /**
     * Classes to autoload & initialize even when not used
     */
// 'classes'  => array(),

    /**
     * Configs to autoload
     *
     * Examples: if you want to load 'session' config into a group 'session' you only have to
     * add 'session'. If you want to add it to another group (example: 'auth') you have to
     * add it like 'session' => 'auth'.
     * If you don't want the config in a group use null as groupname.
     */
// 'config'  => array(),

    /**
     * Language files to autoload
     *
     * Examples: if you want to load 'validation' lang into a group 'validation' you only have to
     * add 'validation'. If you want to add it to another group (example: 'forms') you have to
     * add it like 'validation' => 'forms'.
     * If you don't want the lang in a group use null as groupname.
     */
// 'language'  => array(),
// ),
//'controller_prefix' => 'Controller\\',
    'always_load' => array(
        'packages' => array(
            'loglib',
            'email',
            'orm',            
        ),
    ),
    'log_threshold' => Fuel::L_DEBUG,
    'log_path' => APPPATH . 'logs/',
    'log_date_format' => 'Y-m-d H:i:s',
    'log_path_bk' => APPPATH . 'logs_bk/',
    'log_bk_after' => 'y',
    'thumbs' => array(
        'places' => array('200x200')
    ),
    'image_ext' => array('jpeg', 'jpg', 'gif', 'png'),
    'video_ext' => array('mp4', 'flv'),
    'time_batch' => 2 * 60,
    'bitly' => array(
        'url' => 'http://api.bit.ly/v3/shorten',
        'auth' => array(
            'login' => 'o_48kuo4o339',
            'apiKey' => 'R_d5e17b2e3a9f7ead889e83dc81ce2cc5'
        ),
        'timeout' => 30,
    ),
    'os' => array(
        'webos' => 'webos',
        'ios' => 'ios',
        'android' => 'android',
    ),
    'system_email' => array(
        'noreply' => 'info@bmaps.world',
        'support' => 'info@bmaps.world',
        'bcc' => 'info@bmaps.world',
    ),
    'register_token_expire' => time() + 60 * 60, // 1 hour
    'api_token_expire' => time() + 30 * 24 * 60 * 60, // 30 days
    'user_activations_type' => array(
        'register_user' => 'register_user', // customer
        'forget_password' => 'forget_password', // forget password      
    ),

    'first_month_of_school_year' => 4, // the month which start school year (In Japan, this is April)

    // page and limit default when they aren't been defined
    'page_default' => '1',
    'limit_default' => '10',
    'limit_nail_relation' => '3',

    // share type
    'facebook_share_type' => '1',
    'twitter_share_type' => '2',
    'google_share_type' => '3',

    // login device
    'ios_login_device' => '1',
    'android_login_device' => '2',
    'web_login_device' => '3',
    'other_login_device' => '0',

    'facebook' => array(
        'app_id' => '485631328262139',
        'app_secret' => 'd1216f4abf31b6c75082d646bdaeceda',
    ),
    'twitter' => array(
        'key' => 'QEo3QaWc4TLCyxkO4KqdBR29u',
        'secret' => '3oIUTkiFL7WkesWyd7iw22luK0YEv2eNxPnjbvaFklh4vqGpJT'
    ),    
    'gmap' => array(       
        'keys' => array(            
            'AIzaSyAkniFEh0LtxGIcA-75nFxY19sJkw7DNE8',
            'AIzaSyA7uAULvlelyQkhfb_-OULb23XiQmFbCeU',
            'AIzaSyApz1dkbMf45cpi9UykvWLG1PJDtuhrS3Y',
            'AIzaSyAaadxQ2C8h7zYEwWSqZCs_cmrskIqu9lU',
            'AIzaSyBJwaEPeApZUE3hsphAkSm3W1rgKJUe7Xg',
            'AIzaSyCW05_iUxdsHCQv1etRg3qM0laUDaGauPk',
            'AIzaSyBKQYlmCr_i4rSdU08nYwsqIiVkgXcIBBY',
            'AIzaSyDjwaFYx9U5_u2OsCUe5S3paQNujBug628', 
            'AIzaSyCnU7ydPUoNPDQUYbh_lD4lAWzb0d2MplI',           
            'AIzaSyBdQFes-x087Ai4FIyjzg_L9E6hfEcMlTk',            
            'AIzaSyAmfeeFC9SgCTJAsF0G9wNgDHeHCA9P0o8',
            'AIzaSyCWlAuG3UgOpKFSF-j-FGuT2R7qvGy0lII'            
        ),
        'radius' => 1000,
        'language' => array(
            1 => 'ja',
            2 => 'en',
            3 => 'th',
            4 => 'vi',
            5 => 'es',
        )
    ),

    // Config limit user to push_message
    'limit_user_push_message'=> 100,

    'authorize' => true,
    'unauthorize_url' => array(
        'admins/login',        
    ),
    'admin_authorize_url' => array(
        'users/addupdate',
        'users/list',
        'users/all',
        'users/disable',
        'users/detail',
        '/adminnotices/addupdate',
        '/adminnotices/detail',
        '/adminnotices/list',
        '/admins/addupdate',
        '/admins/detail',
        '/admins/disable',
        '/admins/list',
        '/admins/updatepassword',
        '/adminsettings/addupdate',
        '/adminsettings/all',
        '/adminsettings/disable',
        '/adminsettings/multiupdate',
        '/reports/dau',
        '/reports/general',
        '/settings/addupdate',
        '/settings/all',
        '/settings/detail',
        '/settings/list',
        '/settings/multiupdate',
        '/system/deletecache',
        'test/list',
    ),

    'unauthorize_basic_token_url' => array(
        'system/deletecache',
    ),
    
    'need_to_add_google_place_url' => array(
        'places/wanttovisit',
        'placeinformations/addupdate',       
        'placereviewpointlogs/add',
        'followplaces/add',
        'placefavorites/add',
        'places/addupdate',
    ),

    'api_check_security' => false,
    'api_secret_key' => 'bmaps',
    'api_request_minute' => 10, // 10 minutes
    //'format.json.encode.options' => JSON_NUMERIC_CHECK
    // login failed config
    'api_loginfailed_limit' => 10,
    'api_loginfailed_reset' => 30, // 30 minutes

    'notice_string' => array(
        1 => array( // follow user
            1 => array( // jp - japanese
                'single' => '%sさんがあなたをフォローしました。',
                'two' => '%sさんと%sさんがあなたをフォローしました。',
                'multi'  => '%sさんと他%s人があなたをフォローしました。'
            ),
            2 => array( // en - english
                'single' => '%s followed you',
                'two' => '%s and %s followed you',
                'multi'  => '%s and %s followed you'
            ),
            3 => array( // th - thai
                'single' => '%sさんがあなたをフォローしました。',
                'two' => '%sさんと%sさんがあなたをフォローしました。',
                'multi'  => '%sさんと他%s人があなたをフォローしました。'
            ),
            4 => array( // vn - vietnamese
                'single' => '%sさんがあなたをフォローしました。',
                'two' => '%sさんと%sさんがあなたをフォローしました。',
                'multi'  => '%sさんと他%s人があなたをフォローしました。'
            ),
            5 => array( // es - Spain
                'single' => '%s te ha empezado a seguir.',
                'two' => '%s y %s te ha empezado a seguir.',
                'multi'  => '%s y %s personas más te han empezado a seguir.'
            )
        ),
        2 => array( // like review
            1 => array( // jp - japanese
                'single' => '%sさんがあなたが%sについてのレビューに対して「いいね!」と言っています。',
                'two' => '%sさんと%sさんががあなたが%sについてのレビューに対して「いいね!」と言っています。',
                'multi'  => '%sさんと他%s人があなたが%sについてのレビューに対して「いいね!」と言っています。'
            ),
            2 => array( // en - english
                'single' => '%s liked your review in place %s',
                'two' => '%s and %s liked your review in place %s',
                'multi'  => '%s and %s liked your review in place %s'
            ),
            3 => array( // th - thai
                'single' => '%sさんがあなたが%sについてのレビューに対して「いいね!」と言っています。',
                'two' => '%sさんと%sさんががあなたが%sについてのレビューに対して「いいね!」と言っています。',
                'multi'  => '%sさんと他%s人があなたが%sについてのレビューに対して「いいね!」と言っています。'
            ),
            4 => array( // vn - vietnamese
                'single' => '%sさんがあなたが%sについてのレビューに対して「いいね!」と言っています。',
                'two' => '%sさんと%sさんががあなたが%sについてのレビューに対して「いいね!」と言っています。',
                'multi'  => '%sさんと他%s人があなたが%sについてのレビューに対して「いいね!」と言っています。'
            ),
            5 => array( // es - Spain
                'single' => 'A %s le gusta tu valoración sobre %s.',
                'two' => 'A %s y %s le gusta tu valoración sobre %s.',
                'multi'  => 'A %s y %s personas más les gusta tu valoración sobre %s.'
            )
        ),
        3 => array( // comment review
            1 => array( // jp - japanese
                'single' => '%sさんがあなたが%sについてのレビューに対してコメントしました。',
                'two' =>  '%sさんと%sさんがあなたが%sについてのレビューに対してコメントしました,。',
                'multi'  => '%sさんと他%s人があなたが%sについてのレビューに対してコメントしました。'
            ),
            2 => array( // en - english
                'single' => '%s commented on your review in place %s',
                'two' => '%s and %s commented on your review in place %s',
                'multi'  => '%s and %s commented on your review in place %s'
            ),
            3 => array( // th - thai
                'single' => '%sさんがあなたが%sについてのレビューに対してコメントしました。',
                'two' =>  '%sさんと%sさんがあなたが%sについてのレビューに対してコメントしました,。',
                'multi'  => '%sさんと他%s人があなたが%sについてのレビューに対してコメントしました。'
            ),
            4 => array( // vn - vietnamese
                'single' => '%sさんがあなたが%sについてのレビューに対してコメントしました。',
                'two' =>  '%sさんと%sさんがあなたが%sについてのレビューに対してコメントしました,。',
                'multi'  => '%sさんと他%s人があなたが%sについてのレビューに対してコメントしました。'
            ),
            5 => array( // es - Spain
                'single' => '%s ha escrito un comentario sobre tu valoración de %s.',
                'two' =>  '%s y %s ha escrito un comentario sobre tu valoración de %s.',
                'multi'  => '%s y %s personas más han escrito un comentario sobre tu valoración de %s.'
            )
        )
    ),
    
    'notices' => array(
        'type' => array(
            'follow_user' => 1,
            'like_review' => 2,
            'comment_review' => 3,
        )
    ),
    
    'google_urlshortener' => array(
        'url' => 'https://www.googleapis.com/urlshortener/v1/url',
        'key' => 'AIzaSyDORv1kNObIyAhI9khTjsiX230_dL7xUI4',
        'timeout' => 30,
    ),
    
    'violation_reports' => array(
        'jp' => array (           
            array ('id' => 1, 'message' => '公序良俗に反する内容の投稿'),
            array ('id' => 2, 'message' => '実際の情報と異なる内容の投稿'),
            array ('id' => 3, 'message' => '移転・閉店により'),
        ), 
        'en' => array (
            array ('id' => 1, 'message' => 'Content posted contrary to public order and morals'),
            array ('id' => 2, 'message' => 'Actual information with different content posts'),
            array ('id' => 3, 'message' => 'By the relocation and closing'),
        ), 
        'th' => array (
            array ('id' => 1, 'message' => 'โพสต์เนื้อหาที่ขัดต่อความสงบเรียบร้อยและศีลธรรม'),
            array ('id' => 2, 'message' => 'ข้อมูลที่เกิดขึ้นจริงกับโพสต์เนื้อหาที่แตกต่าง'),
            array ('id' => 3, 'message' => 'โดยการย้ายถิ่นฐานและปิด'),
        ),
        'es' => array (           
            array ('id' => 1, 'message' => 'Publicación de dudosa moralidad'),
            array ('id' => 2, 'message' => 'Publicación que no corresponde con la realidad'),
            array ('id' => 3, 'message' => 'Debido a traspaso o cierre'),
        ),
    ),    

    'teams_section' => array(
        'jp' => array (        
            array ('id' => 1, 'name' => '一般'),
            array ('id' => 2, 'name' => '企業'),
            array ('id' => 3, 'name' => '大学'),             
        ), 
        'en' => array (
            array ('id' => 1, 'name' => 'General'),
            array ('id' => 2, 'name' => 'Company'),
            array ('id' => 3, 'name' => 'University'),
        ), 
        'th' => array (
            array ('id' => 1, 'name' => 'General'),
            array ('id' => 2, 'name' => 'Company'),
            array ('id' => 3, 'name' => 'University'),
        ),
        'es' => array (
            array ('id' => 1, 'name' => 'General'),
            array ('id' => 2, 'name' => 'Empresa'),
            array ('id' => 3, 'name' => 'Universidad'),
        ),
    ),
    
    'user_points_type' => array(// use for Team point
        '1' => 1, // review_spot => point
        '2' => 1, // add_spot => point
        '3' => 0, // add_comment => point
        '4' => 0, // want_to_visit => point
    ),
    
    'user_point_logs' => array(// Use for Bcoin
        'type' => array(
            'review_spot' => 1,
            'add_spot' => 2,
        )
    ),
    'point_gets' => array(
        'id' => array( // ID in table "point_gets"
            'review_spot' => 1,
            'add_spot' => 2,
        )
    ),
    'email_subject' => array(
        'forget_password' => array(
            1 => 'パスワード再設定手続きのお知らせ',
            2 => 'パスワード再設定手続きのお知らせ',
            3 => 'パスワード再設定手続きのお知らせ',
            4 => 'パスワード再設定手続きのお知らせ',
            5 => 'パスワード再設定手続きのお知らせ',
        ),
        'create_user' => array(
            1 => 'Bmaps 仮登録',
            2 => 'Bmaps 仮登録',
            3 => 'Bmaps 仮登録',
            4 => 'Bmaps 仮登録',
            5 => 'Bmaps 仮登録',
        ),
        'register' => array(
            1 => '会員登録頂きまして誠に有難うございました。',
            2 => '会員登録頂きまして誠に有難うございました。',
            3 => '会員登録頂きまして誠に有難うございました。',
            4 => '会員登録頂きまして誠に有難うございました。',
            5 => '会員登録頂きまして誠に有難うございました。',
        ),
        'register_active' => array(
            1 => 'Bmaps 登録完了',
            2 => 'Bmaps 登録完了',
            3 => 'Bmaps 登録完了',
            4 => 'Bmaps 登録完了',
            5 => 'Bmaps 登録完了',
        ),
        'cancel_user' => array(
            1 => '退会処理が完了しました',
            2 => '退会処理が完了しました',
            3 => '退会処理が完了しました',
            4 => '退会処理が完了しました',
            5 => '退会処理が完了しました',
        ),
        'landing' => array(
            1 => '【Bmaps.world】お問い合わせありがとうございました。',
            2 => '[Bmaps.world] Thank you for your contact',
            3 => '【Bmaps.world】お問い合わせありがとうございました。',
            4 => '【Bmaps.world】お問い合わせありがとうございました。',
            5 => '[Bmaps.world] Gracias por contactar con',
        ),
    ),
);
